services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/avani-srivastavaa/pdf-generator
    branch: main
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    autoDeploy: true

  - type: web
    name: frontend
    env: static
    repo: https://github.com/avani-srivastavaa/pdf-generator
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    buildFilter:
      paths:
        - frontend/**
    autoDeploy: true
